USE sakila;

-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.

SELECT c.name AS category_name, COUNT(f.film_id) AS number_of_films
FROM film f
    INNER JOIN film_category fc ON f.film_id = fc.film_id
    INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT s.store_id, c.city, co.country 
FROM store s
	JOIN address ad ON s.address_id = ad.address_id
    JOIN city c on ad.city_id = c.city_id
    JOIN country co on c.country_id = co.country_id;
    
-- 3. Calculate the total revenue generated by each store in dollars.

SELECT staff_id AS store, SUM(amount) FROM payment 
GROUP BY staff_id;

-- 4. Determine the average running time of films for each category.

SELECT c.name AS category, AVG(f.length) 
FROM category c 
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f on fc.film_id = f.film_id
GROUP BY category;
	